message:
  BeerInventoryService-replica04
spring:
  profiles: replica04
eureka:
  instance:
    appname: BeerInventoryService  # ==> This is a instance of ABC-SERVICE
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://my-eureka-server-us.com:9001/eureka
      #defaultZone: http://my-eureka-server.com:9000/eureka
      #defaultZone: http://my-eureka-server-fr.com:9002/eureka
      #defaultZone: http://my-eureka-server-vn.com:9003/eureka
server:
  port: 8004