message:
  DiscoveryCloudService-france
spring:
  profiles: france
  application:
    name: EurekaServerClustered   # ==> This is Service-Id
server:
  port: 9002
eureka:
  instance:
    hostname: my-eureka-server-fr.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://my-eureka-server-us.com:9001/eureka/,http://my-eureka-server-vn.com:9003/eureka/
