message:
  EurekaServerClustered-usa
spring:
  profiles: usa
  application:
    name: EurekaServerClustered   # ==> This is Service-Id
server:
  port: 9001
eureka:
  instance:
    hostname: my-eureka-server-us.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://my-eureka-server-fr.com:9002/eureka/,http://my-eureka-server-vn.com:9003/eureka/
