message:
  EurekaServerClustered-vietnam
spring:
  profiles: vietnam
  application:
    name: EurekaServerClustered    # ==> This is Service-Id
server:
  port: 9003
eureka:
  instance:
    hostname: my-eureka-server-vn.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://my-eureka-server-us.com:9001/eureka/,http://my-eureka-server-fr.com:9002/eureka/
